2020-04-23 11:43:58,482 ERROR: Exception on /login [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 51, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/login.html", line 25, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Reset</a>
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-04-23 11:44:01,909 ERROR: Exception on /login [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 51, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/login.html", line 25, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Reset</a>
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-04-23 13:55:59,433 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 13:58:57,254 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 11, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2020-04-23 13:59:18,136 ERROR: Exception on /reset_password_request [POST] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 62, in reset_password_request
    send_password_reset_email(user)
  File "/mnt/c/Users/mohit/Desktop/blog/app/email.py", line 11, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2020-04-23 14:04:10,708 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
