2020-04-13 18:45:05,283 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 18:47:31,303 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 19:21:13,252 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 19:21:22,093 ERROR: Exception on /explore [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 72, in explore
    next_url=next_url, prev_url=prev_url)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/_post.html", line 11, in template
    says: <br>{{ post.body }}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.
2020-04-13 19:21:47,068 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-13 19:21:48,144 ERROR: Exception on / [GET] [in /mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/mohit/Desktop/blog/app/routes.py", line 34, in index
    next_url=next_url, prev_url=prev_url)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/mohit/Desktop/blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/mohit/Desktop/blog/app/templates/_post.html", line 5, in template
    {% if username is not post.author.username %}
jinja2.exceptions.TemplateAssertionError: no test named 'post.author.username'
2020-04-13 19:37:30,875 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-15 12:02:10,720 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:55]
2020-04-22 23:28:58,573 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 00:03:52,190 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 00:06:47,491 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 00:09:55,287 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
2020-04-23 11:43:40,105 INFO: Microblog startup [in /mnt/c/Users/mohit/Desktop/blog/app/__init__.py:54]
